namespace: hoeze
name: conda
version: 2.0.0
readme: README.md
authors:
  - Florian R. Hölzlwimmer (github.com/hoeze)
description: >-
  This collection provides Ansible modules and plugins for managing Conda
  environments, enabling users to automate the setup and maintenance of
  Conda-based environments.
license_file: LICENSE
tags:
  - conda
  - anaconda
  - environment
  - mamba
  - package
repository: https://github.com/hoeze/ansible-collection-conda
homepage: https://github.com/hoeze/ansible-collection-conda
issues: https://github.com/hoeze/ansible-collection-conda/issues
build_ignore:
  - .github
  - .gitignore
  - .release-please-manifest.json
  - release-please-config.json
  - roles/conda_env_tests
